language: go
sudo: false
go:
  - "1.9.x"
  - "1.10"
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
script:
  - go test ./lib -coverprofile=coverage.txt -covermode=atomic
install:
  - go get -v -d -t ./...
